modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="dcclasses"
version="1.1.0a"
displayName="DawnCraft Classes"
displayURL=""
updateJSONURL=""
credits=""
authors="Smileycorp"
description=""
